/*
 * generated by Xtext 2.9.0
 */
package org.xtext.example.tfg.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractMyDslScopeProvider extends XbaseBatchScopeProvider {
}
