/*
 * generated by Xtext 2.9.0
 */
package org.xtext.example.tfg.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.tfg.ui.internal.TfgActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TfgActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TfgActivator.getInstance().getInjector(TfgActivator.ORG_XTEXT_EXAMPLE_TFG_MYDSL);
	}
	
}
