/**
 * generated by Xtext 2.9.0
 */
package org.xtext.example.tfg.myDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.tfg.myDsl.ATTRIBUTE;
import org.xtext.example.tfg.myDsl.MyDslPackage;
import org.xtext.example.tfg.myDsl.VALUEOBJECT;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>VALUEOBJECT</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.tfg.myDsl.impl.VALUEOBJECTImpl#getValueattributes <em>Valueattributes</em>}</li>
 * </ul>
 *
 * @generated
 */
public class VALUEOBJECTImpl extends ELEMENTImpl implements VALUEOBJECT
{
  /**
   * The cached value of the '{@link #getValueattributes() <em>Valueattributes</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValueattributes()
   * @generated
   * @ordered
   */
  protected EList<ATTRIBUTE> valueattributes;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected VALUEOBJECTImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.VALUEOBJECT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<ATTRIBUTE> getValueattributes()
  {
    if (valueattributes == null)
    {
      valueattributes = new EObjectContainmentEList<ATTRIBUTE>(ATTRIBUTE.class, this, MyDslPackage.VALUEOBJECT__VALUEATTRIBUTES);
    }
    return valueattributes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.VALUEOBJECT__VALUEATTRIBUTES:
        return ((InternalEList<?>)getValueattributes()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.VALUEOBJECT__VALUEATTRIBUTES:
        return getValueattributes();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.VALUEOBJECT__VALUEATTRIBUTES:
        getValueattributes().clear();
        getValueattributes().addAll((Collection<? extends ATTRIBUTE>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.VALUEOBJECT__VALUEATTRIBUTES:
        getValueattributes().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.VALUEOBJECT__VALUEATTRIBUTES:
        return valueattributes != null && !valueattributes.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //VALUEOBJECTImpl
