/**
 * generated by Xtext 2.9.0
 */
package org.xtext.example.tfg.myDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>ENTITY</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.tfg.myDsl.ENTITY#isAbstractEntity <em>Abstract Entity</em>}</li>
 *   <li>{@link org.xtext.example.tfg.myDsl.ENTITY#getParent <em>Parent</em>}</li>
 *   <li>{@link org.xtext.example.tfg.myDsl.ENTITY#getEntityElements <em>Entity Elements</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.tfg.myDsl.MyDslPackage#getENTITY()
 * @model
 * @generated
 */
public interface ENTITY extends ELEMENT
{
  /**
   * Returns the value of the '<em><b>Abstract Entity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Abstract Entity</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Abstract Entity</em>' attribute.
   * @see #setAbstractEntity(boolean)
   * @see org.xtext.example.tfg.myDsl.MyDslPackage#getENTITY_AbstractEntity()
   * @model
   * @generated
   */
  boolean isAbstractEntity();

  /**
   * Sets the value of the '{@link org.xtext.example.tfg.myDsl.ENTITY#isAbstractEntity <em>Abstract Entity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Abstract Entity</em>' attribute.
   * @see #isAbstractEntity()
   * @generated
   */
  void setAbstractEntity(boolean value);

  /**
   * Returns the value of the '<em><b>Parent</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parent</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parent</em>' reference.
   * @see #setParent(ENTITY)
   * @see org.xtext.example.tfg.myDsl.MyDslPackage#getENTITY_Parent()
   * @model
   * @generated
   */
  ENTITY getParent();

  /**
   * Sets the value of the '{@link org.xtext.example.tfg.myDsl.ENTITY#getParent <em>Parent</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parent</em>' reference.
   * @see #getParent()
   * @generated
   */
  void setParent(ENTITY value);

  /**
   * Returns the value of the '<em><b>Entity Elements</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.tfg.myDsl.ENTITYELEMENT}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Entity Elements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity Elements</em>' containment reference list.
   * @see org.xtext.example.tfg.myDsl.MyDslPackage#getENTITY_EntityElements()
   * @model containment="true"
   * @generated
   */
  EList<ENTITYELEMENT> getEntityElements();

} // ENTITY
