/**
 * generated by Xtext 2.9.0
 */
package org.xtext.example.tfg.myDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>LINK</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.tfg.myDsl.LINK#getRelations <em>Relations</em>}</li>
 *   <li>{@link org.xtext.example.tfg.myDsl.LINK#getAttributes <em>Attributes</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.tfg.myDsl.MyDslPackage#getLINK()
 * @model
 * @generated
 */
public interface LINK extends ELEMENT
{
  /**
   * Returns the value of the '<em><b>Relations</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.tfg.myDsl.RELATIONSHIP}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Relations</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Relations</em>' containment reference list.
   * @see org.xtext.example.tfg.myDsl.MyDslPackage#getLINK_Relations()
   * @model containment="true"
   * @generated
   */
  EList<RELATIONSHIP> getRelations();

  /**
   * Returns the value of the '<em><b>Attributes</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.tfg.myDsl.ATTRIBUTE}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Attributes</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attributes</em>' containment reference list.
   * @see org.xtext.example.tfg.myDsl.MyDslPackage#getLINK_Attributes()
   * @model containment="true"
   * @generated
   */
  EList<ATTRIBUTE> getAttributes();

} // LINK
