/**
 * generated by Xtext 2.9.0
 */
package org.xtext.example.tfg.myDsl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.tfg.myDsl.MyDslPackage
 * @generated
 */
public interface MyDslFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslFactory eINSTANCE = org.xtext.example.tfg.myDsl.impl.MyDslFactoryImpl.init();

  /**
   * Returns a new object of class '<em>MODEL</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MODEL</em>'.
   * @generated
   */
  MODEL createMODEL();

  /**
   * Returns a new object of class '<em>ELEMENT</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ELEMENT</em>'.
   * @generated
   */
  ELEMENT createELEMENT();

  /**
   * Returns a new object of class '<em>ENTITY</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ENTITY</em>'.
   * @generated
   */
  ENTITY createENTITY();

  /**
   * Returns a new object of class '<em>ENTITYELEMENT</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ENTITYELEMENT</em>'.
   * @generated
   */
  ENTITYELEMENT createENTITYELEMENT();

  /**
   * Returns a new object of class '<em>VALUEOBJECT</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>VALUEOBJECT</em>'.
   * @generated
   */
  VALUEOBJECT createVALUEOBJECT();

  /**
   * Returns a new object of class '<em>ENUMERATION</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ENUMERATION</em>'.
   * @generated
   */
  ENUMERATION createENUMERATION();

  /**
   * Returns a new object of class '<em>LINK</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>LINK</em>'.
   * @generated
   */
  LINK createLINK();

  /**
   * Returns a new object of class '<em>ANNOTATED ATTRIBUTE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ANNOTATED ATTRIBUTE</em>'.
   * @generated
   */
  ANNOTATED_ATTRIBUTE createANNOTATED_ATTRIBUTE();

  /**
   * Returns a new object of class '<em>ATTRIBUTE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ATTRIBUTE</em>'.
   * @generated
   */
  ATTRIBUTE createATTRIBUTE();

  /**
   * Returns a new object of class '<em>RELATIONSHIP</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>RELATIONSHIP</em>'.
   * @generated
   */
  RELATIONSHIP createRELATIONSHIP();

  /**
   * Returns a new object of class '<em>OPERATION</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>OPERATION</em>'.
   * @generated
   */
  OPERATION createOPERATION();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  MyDslPackage getMyDslPackage();

} //MyDslFactory
