/**
 * generated by Xtext 2.9.0
 */
package org.xtext.example.tfg.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>RELATIONSHIP</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.tfg.myDsl.RELATIONSHIP#getCardinal <em>Cardinal</em>}</li>
 *   <li>{@link org.xtext.example.tfg.myDsl.RELATIONSHIP#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.example.tfg.myDsl.RELATIONSHIP#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.tfg.myDsl.MyDslPackage#getRELATIONSHIP()
 * @model
 * @generated
 */
public interface RELATIONSHIP extends EObject
{
  /**
   * Returns the value of the '<em><b>Cardinal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cardinal</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cardinal</em>' attribute.
   * @see #setCardinal(String)
   * @see org.xtext.example.tfg.myDsl.MyDslPackage#getRELATIONSHIP_Cardinal()
   * @model
   * @generated
   */
  String getCardinal();

  /**
   * Sets the value of the '{@link org.xtext.example.tfg.myDsl.RELATIONSHIP#getCardinal <em>Cardinal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cardinal</em>' attribute.
   * @see #getCardinal()
   * @generated
   */
  void setCardinal(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(ENTITY)
   * @see org.xtext.example.tfg.myDsl.MyDslPackage#getRELATIONSHIP_Type()
   * @model
   * @generated
   */
  ENTITY getType();

  /**
   * Sets the value of the '{@link org.xtext.example.tfg.myDsl.RELATIONSHIP#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(ENTITY value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.tfg.myDsl.MyDslPackage#getRELATIONSHIP_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.tfg.myDsl.RELATIONSHIP#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // RELATIONSHIP
