/*
 * generated by Xtext 2.9.0
 */
package org.xtext.example.tfg.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.xtext.example.tfg.ui.internal.TfgActivator;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TfgActivator.getInstance().getInjector("org.xtext.example.tfg.MyDsl");
	}

}
