//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.14 at 03:14:15 PM CET 
//


package model;

import javax.xml.bind.annotation.XmlRegistry;

import model.associations.AssociationOverride;
import model.associations.AttributeOverride;
import model.associations.CascadeType;
import model.associations.JoinColumn;
import model.associations.JoinTable;
import model.associations.ManyToMany;
import model.associations.ManyToOne;
import model.associations.MapKey;
import model.associations.MapKeyClass;
import model.associations.MapKeyColumn;
import model.associations.MapKeyJoinColumn;
import model.associations.OneToMany;
import model.associations.OneToOne;
import model.generators.GeneratedValue;
import model.generators.SequenceGenerator;
import model.generators.TableGenerator;
import model.inheritance.DiscriminatorColumn;
import model.inheritance.IdClass;
import model.inheritance.Inheritance;
import model.inheritance.PrimaryKeyJoinColumn;
import model.lifecycle.EntityListener;
import model.lifecycle.EntityListeners;
import model.lifecycle.PostLoad;
import model.lifecycle.PostPersist;
import model.lifecycle.PostRemove;
import model.lifecycle.PostUpdate;
import model.lifecycle.PrePersist;
import model.lifecycle.PreRemove;
import model.lifecycle.PreUpdate;
import model.queries.ColumnResult;
import model.queries.ConstructorResult;
import model.queries.Convert;
import model.queries.Converter;
import model.queries.EntityResult;
import model.queries.FieldResult;
import model.queries.NamedAttributeNode;
import model.queries.NamedEntityGraph;
import model.queries.NamedNativeQuery;
import model.queries.NamedQuery;
import model.queries.NamedStoredProcedureQuery;
import model.queries.NamedSubgraph;
import model.queries.OrderColumn;
import model.queries.QueryHint;
import model.queries.SqlResultSetMapping;
import model.queries.StoredProcedureParameter;
import model.structure.Attributes;
import model.structure.Basic;
import model.structure.CollectionTable;
import model.structure.Column;
import model.structure.ElementCollection;
import model.structure.Embeddable;
import model.structure.EmbeddableAttributes;
import model.structure.Embedded;
import model.structure.EmbeddedId;
import model.structure.EmptyType;
import model.structure.Entity;
import model.structure.EntityMappings;
import model.structure.ForeignKey;
import model.structure.Id;
import model.structure.Index;
import model.structure.Lob;
import model.structure.MappedSuperclass;
import model.structure.SecondaryTable;
import model.structure.Table;
import model.structure.Transient;
import model.structure.UniqueConstraint;
import model.structure.Version;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.jcp.xmlns.xml.ns.persistence.orm package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.jcp.xmlns.xml.ns.persistence.orm
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EntityMappings }
     * 
     */
    public EntityMappings createEntityMappings() {
        return new EntityMappings();
    }

    /**
     * Create an instance of {@link PersistenceUnitMetadata }
     * 
     */
    public PersistenceUnitMetadata createPersistenceUnitMetadata() {
        return new PersistenceUnitMetadata();
    }

    /**
     * Create an instance of {@link SequenceGenerator }
     * 
     */
    public SequenceGenerator createSequenceGenerator() {
        return new SequenceGenerator();
    }

    /**
     * Create an instance of {@link TableGenerator }
     * 
     */
    public TableGenerator createTableGenerator() {
        return new TableGenerator();
    }

    /**
     * Create an instance of {@link NamedQuery }
     * 
     */
    public NamedQuery createNamedQuery() {
        return new NamedQuery();
    }

    /**
     * Create an instance of {@link NamedNativeQuery }
     * 
     */
    public NamedNativeQuery createNamedNativeQuery() {
        return new NamedNativeQuery();
    }

    /**
     * Create an instance of {@link NamedStoredProcedureQuery }
     * 
     */
    public NamedStoredProcedureQuery createNamedStoredProcedureQuery() {
        return new NamedStoredProcedureQuery();
    }

    /**
     * Create an instance of {@link SqlResultSetMapping }
     * 
     */
    public SqlResultSetMapping createSqlResultSetMapping() {
        return new SqlResultSetMapping();
    }

    /**
     * Create an instance of {@link MappedSuperclass }
     * 
     */
    public MappedSuperclass createMappedSuperclass() {
        return new MappedSuperclass();
    }

    /**
     * Create an instance of {@link Entity }
     * 
     */
    public Entity createEntity() {
        return new Entity();
    }

    /**
     * Create an instance of {@link Embeddable }
     * 
     */
    public Embeddable createEmbeddable() {
        return new Embeddable();
    }

    /**
     * Create an instance of {@link Converter }
     * 
     */
    public Converter createConverter() {
        return new Converter();
    }

    /**
     * Create an instance of {@link PersistenceUnitDefaults }
     * 
     */
    public PersistenceUnitDefaults createPersistenceUnitDefaults() {
        return new PersistenceUnitDefaults();
    }

    /**
     * Create an instance of {@link Inheritance }
     * 
     */
    public Inheritance createInheritance() {
        return new Inheritance();
    }

    /**
     * Create an instance of {@link Convert }
     * 
     */
    public Convert createConvert() {
        return new Convert();
    }

    /**
     * Create an instance of {@link AssociationOverride }
     * 
     */
    public AssociationOverride createAssociationOverride() {
        return new AssociationOverride();
    }

    /**
     * Create an instance of {@link ConstructorResult }
     * 
     */
    public ConstructorResult createConstructorResult() {
        return new ConstructorResult();
    }

    /**
     * Create an instance of {@link MapKeyClass }
     * 
     */
    public MapKeyClass createMapKeyClass() {
        return new MapKeyClass();
    }

    /**
     * Create an instance of {@link Id }
     * 
     */
    public Id createId() {
        return new Id();
    }

    /**
     * Create an instance of {@link ColumnResult }
     * 
     */
    public ColumnResult createColumnResult() {
        return new ColumnResult();
    }

    /**
     * Create an instance of {@link NamedSubgraph }
     * 
     */
    public NamedSubgraph createNamedSubgraph() {
        return new NamedSubgraph();
    }

    /**
     * Create an instance of {@link PostPersist }
     * 
     */
    public PostPersist createPostPersist() {
        return new PostPersist();
    }

    /**
     * Create an instance of {@link MapKey }
     * 
     */
    public MapKey createMapKey() {
        return new MapKey();
    }

    /**
     * Create an instance of {@link StoredProcedureParameter }
     * 
     */
    public StoredProcedureParameter createStoredProcedureParameter() {
        return new StoredProcedureParameter();
    }

    /**
     * Create an instance of {@link GeneratedValue }
     * 
     */
    public GeneratedValue createGeneratedValue() {
        return new GeneratedValue();
    }

    /**
     * Create an instance of {@link CascadeType }
     * 
     */
    public CascadeType createCascadeType() {
        return new CascadeType();
    }

    /**
     * Create an instance of {@link Index }
     * 
     */
    public Index createIndex() {
        return new Index();
    }

    /**
     * Create an instance of {@link SecondaryTable }
     * 
     */
    public SecondaryTable createSecondaryTable() {
        return new SecondaryTable();
    }

    /**
     * Create an instance of {@link Version }
     * 
     */
    public Version createVersion() {
        return new Version();
    }

    /**
     * Create an instance of {@link ManyToMany }
     * 
     */
    public ManyToMany createManyToMany() {
        return new ManyToMany();
    }

    /**
     * Create an instance of {@link PostUpdate }
     * 
     */
    public PostUpdate createPostUpdate() {
        return new PostUpdate();
    }

    /**
     * Create an instance of {@link Transient }
     * 
     */
    public Transient createTransient() {
        return new Transient();
    }

    /**
     * Create an instance of {@link EntityListeners }
     * 
     */
    public EntityListeners createEntityListeners() {
        return new EntityListeners();
    }

    /**
     * Create an instance of {@link EmbeddableAttributes }
     * 
     */
    public EmbeddableAttributes createEmbeddableAttributes() {
        return new EmbeddableAttributes();
    }

    /**
     * Create an instance of {@link EntityResult }
     * 
     */
    public EntityResult createEntityResult() {
        return new EntityResult();
    }

    /**
     * Create an instance of {@link Basic }
     * 
     */
    public Basic createBasic() {
        return new Basic();
    }

    /**
     * Create an instance of {@link NamedAttributeNode }
     * 
     */
    public NamedAttributeNode createNamedAttributeNode() {
        return new NamedAttributeNode();
    }

    /**
     * Create an instance of {@link OneToMany }
     * 
     */
    public OneToMany createOneToMany() {
        return new OneToMany();
    }

    /**
     * Create an instance of {@link Lob }
     * 
     */
    public Lob createLob() {
        return new Lob();
    }

    /**
     * Create an instance of {@link OrderColumn }
     * 
     */
    public OrderColumn createOrderColumn() {
        return new OrderColumn();
    }

    /**
     * Create an instance of {@link PostRemove }
     * 
     */
    public PostRemove createPostRemove() {
        return new PostRemove();
    }

    /**
     * Create an instance of {@link MapKeyColumn }
     * 
     */
    public MapKeyColumn createMapKeyColumn() {
        return new MapKeyColumn();
    }

    /**
     * Create an instance of {@link MapKeyJoinColumn }
     * 
     */
    public MapKeyJoinColumn createMapKeyJoinColumn() {
        return new MapKeyJoinColumn();
    }

    /**
     * Create an instance of {@link DiscriminatorColumn }
     * 
     */
    public DiscriminatorColumn createDiscriminatorColumn() {
        return new DiscriminatorColumn();
    }

    /**
     * Create an instance of {@link AttributeOverride }
     * 
     */
    public AttributeOverride createAttributeOverride() {
        return new AttributeOverride();
    }

    /**
     * Create an instance of {@link PrePersist }
     * 
     */
    public PrePersist createPrePersist() {
        return new PrePersist();
    }

    /**
     * Create an instance of {@link JoinColumn }
     * 
     */
    public JoinColumn createJoinColumn() {
        return new JoinColumn();
    }

    /**
     * Create an instance of {@link JoinTable }
     * 
     */
    public JoinTable createJoinTable() {
        return new JoinTable();
    }

    /**
     * Create an instance of {@link QueryHint }
     * 
     */
    public QueryHint createQueryHint() {
        return new QueryHint();
    }

    /**
     * Create an instance of {@link PreUpdate }
     * 
     */
    public PreUpdate createPreUpdate() {
        return new PreUpdate();
    }

    /**
     * Create an instance of {@link PreRemove }
     * 
     */
    public PreRemove createPreRemove() {
        return new PreRemove();
    }

    /**
     * Create an instance of {@link Embedded }
     * 
     */
    public Embedded createEmbedded() {
        return new Embedded();
    }

    /**
     * Create an instance of {@link Table }
     * 
     */
    public Table createTable() {
        return new Table();
    }

    /**
     * Create an instance of {@link UniqueConstraint }
     * 
     */
    public UniqueConstraint createUniqueConstraint() {
        return new UniqueConstraint();
    }

    /**
     * Create an instance of {@link EmbeddedId }
     * 
     */
    public EmbeddedId createEmbeddedId() {
        return new EmbeddedId();
    }

    /**
     * Create an instance of {@link ManyToOne }
     * 
     */
    public ManyToOne createManyToOne() {
        return new ManyToOne();
    }

    /**
     * Create an instance of {@link NamedEntityGraph }
     * 
     */
    public NamedEntityGraph createNamedEntityGraph() {
        return new NamedEntityGraph();
    }

    /**
     * Create an instance of {@link Column }
     * 
     */
    public Column createColumn() {
        return new Column();
    }

    /**
     * Create an instance of {@link OneToOne }
     * 
     */
    public OneToOne createOneToOne() {
        return new OneToOne();
    }

    /**
     * Create an instance of {@link ElementCollection }
     * 
     */
    public ElementCollection createElementCollection() {
        return new ElementCollection();
    }

    /**
     * Create an instance of {@link EntityListener }
     * 
     */
    public EntityListener createEntityListener() {
        return new EntityListener();
    }

    /**
     * Create an instance of {@link PrimaryKeyJoinColumn }
     * 
     */
    public PrimaryKeyJoinColumn createPrimaryKeyJoinColumn() {
        return new PrimaryKeyJoinColumn();
    }

    /**
     * Create an instance of {@link PostLoad }
     * 
     */
    public PostLoad createPostLoad() {
        return new PostLoad();
    }

    /**
     * Create an instance of {@link CollectionTable }
     * 
     */
    public CollectionTable createCollectionTable() {
        return new CollectionTable();
    }

    /**
     * Create an instance of {@link FieldResult }
     * 
     */
    public FieldResult createFieldResult() {
        return new FieldResult();
    }

    /**
     * Create an instance of {@link EmptyType }
     * 
     */
    public EmptyType createEmptyType() {
        return new EmptyType();
    }

    /**
     * Create an instance of {@link Attributes }
     * 
     */
    public Attributes createAttributes() {
        return new Attributes();
    }

    /**
     * Create an instance of {@link ForeignKey }
     * 
     */
    public ForeignKey createForeignKey() {
        return new ForeignKey();
    }

    /**
     * Create an instance of {@link IdClass }
     * 
     */
    public IdClass createIdClass() {
        return new IdClass();
    }

}
